import { readFileSync, writeFileSync, readdirSync } from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { brands, type BrandProfile } from "@stak/shared";
import type { BrandDraft } from "./brandGenerationService.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
// backend/src/services -> repo root -> shared/src
const SHARED_SRC_DIR = path.resolve(__dirname, "../../../shared/src");
const BRANDS_DIR = path.join(SHARED_SRC_DIR, "brands");
const STOCKTAGS_FILE = path.join(SHARED_SRC_DIR, "stockTags.ts");

// ── Generic recursive serializer, parameterized by indent unit so appended
// entries match whichever style the target file already uses (tabs in the
// chunk files, two spaces in stockTags.ts) without reformatting anything
// already there. ──────────────────────────────────────────────────────────────

export function serialize(value: unknown, indentUnit: string, depth: number): string {
	const pad = indentUnit.repeat(depth);
	const padIn = indentUnit.repeat(depth + 1);
	if (value === null) return "null";
	if (Array.isArray(value)) {
		if (value.length === 0) return "[]";
		const items = value.map((v) => `${padIn}${serialize(v, indentUnit, depth + 1)}`).join(",\n");
		return `[\n${items},\n${pad}]`;
	}
	if (typeof value === "object") {
		const entries = Object.entries(value as Record<string, unknown>).filter(([, v]) => v !== undefined);
		if (entries.length === 0) return "{}";
		const body = entries
			.map(([k, v]) => `${padIn}${JSON.stringify(k)}: ${serialize(v, indentUnit, depth + 1)}`)
			.join(",\n");
		return `{\n${body},\n${pad}}`;
	}
	return JSON.stringify(value);
}

// Entries written here have exactly 1 tab of indent before their opening
// brace (depth 1 inside the top-level array) -- no nested structure inside a
// brand entry sits at that exact depth, so this reliably counts top-level
// entries without needing a full parse.
const CHUNK_ENTRY_OPEN_BRACE = /\r?\n\t\{\r?\n/g;

export function countEntries(fileText: string): number {
	return [...fileText.matchAll(CHUNK_ENTRY_OPEN_BRACE)].length;
}

function chunkFileName(num: number): string {
	return `chunk-${String(num).padStart(2, "0")}.ts`;
}

function chunkExportName(num: number): string {
	return `brandsChunk${String(num).padStart(2, "0")}`;
}

// New entries keep landing in the same last chunk file forever otherwise,
// which defeats chunking's whole point (diff/review/IDE ergonomics) as the
// catalog grows toward ~2000 entries -- roll over to a new chunk file once
// the last one is already at/over this cap, rather than letting one file
// absorb most of the catalog's future growth.
const CHUNK_SIZE_CAP = 150;

function findLastChunkFile(): { fileName: string; exportName: string; num: number; currentCount: number } {
	const files = readdirSync(BRANDS_DIR).filter((f) => /^chunk-\d+\.ts$/.test(f)).sort();
	if (files.length === 0) throw new Error(`No chunk-NN.ts files found in ${BRANDS_DIR}`);
	const lastFile = files[files.length - 1]!;
	const num = parseInt(lastFile.match(/chunk-(\d+)\.ts/)![1]!, 10);
	const fileText = readFileSync(path.join(BRANDS_DIR, lastFile), "utf-8");
	return { fileName: lastFile, exportName: chunkExportName(num), num, currentCount: countEntries(fileText) };
}

/** Adds `import { brandsChunkNN } from "./chunk-NN";` after the last existing
 * chunk import, and `...brandsChunkNN,` into the rawBrands array, in
 * shared/src/brands/index.ts -- needed only when findLastChunkFile() decides
 * to start a new chunk file instead of appending to the existing last one. */
function registerNewChunkInIndex(num: number): void {
	const indexPath = path.join(BRANDS_DIR, "index.ts");
	const fileText = readFileSync(indexPath, "utf-8");
	const exportName = chunkExportName(num);
	const importLine = `import { ${exportName} } from "./${chunkFileName(num).replace(/\.ts$/, "")}";`;

	const lastImportMatch = [...fileText.matchAll(/^import \{ brandsChunk\d+ \} from "\.\/chunk-\d+";\r?\n/gm)].pop();
	if (!lastImportMatch) throw new Error("Could not find existing chunk imports in brands/index.ts to insert after");
	const afterLastImport = lastImportMatch.index! + lastImportMatch[0].length;
	let updated = fileText.slice(0, afterLastImport) + importLine + "\r\n" + fileText.slice(afterLastImport);

	updated = appendBeforeArrayClose(updated, "];", `\t...${exportName},\r\n`);
	writeFileSync(indexPath, updated);
}

export function createNewChunkFile(num: number, newBrands: BrandProfile[]): { fileName: string; exportName: string } {
	const fileName = chunkFileName(num);
	const exportName = chunkExportName(num);
	const entriesText = newBrands.map((b) => `\t${serialize(b, "\t", 1)},\r\n`).join("");
	const content = `import type { BrandProfile } from "./types";\r\n\r\n// Auto-generated by the brand-generation commit tool -- do not hand-edit structure,\r\n// only add/edit entries. ${newBrands.length} brands.\r\nexport const ${exportName}: BrandProfile[] = [\r\n${entriesText}];\r\n`;
	writeFileSync(path.join(BRANDS_DIR, fileName), content);
	registerNewChunkInIndex(num);
	return { fileName, exportName };
}

/** Inserts new entries right before a file's final top-level array's closing
 * bracket, leaving every byte before that point untouched (except adding a
 * trailing comma after the current last entry if it doesn't already have one
 * -- some existing files were authored without trailing commas on the last
 * item, which is otherwise valid JS/TS but breaks a naive text splice).
 * `closeMarker` is the exact text immediately after the array's last entry
 * (e.g. "];" or "] as const;"). */
export function appendBeforeArrayClose(fileText: string, closeMarker: string, newEntriesText: string): string {
	const idx = fileText.lastIndexOf(closeMarker);
	if (idx === -1) throw new Error(`Could not find "${closeMarker}" in file to append before`);

	let insertAt = idx;
	let lastChar = idx - 1;
	while (lastChar >= 0 && /\s/.test(fileText[lastChar]!)) lastChar--;
	if (lastChar >= 0 && fileText[lastChar] !== ",") {
		insertAt = lastChar + 1;
		return fileText.slice(0, insertAt) + "," + fileText.slice(insertAt, idx) + newEntriesText + fileText.slice(idx);
	}

	return fileText.slice(0, insertAt) + newEntriesText + fileText.slice(insertAt);
}

function appendBrandsToChunk(newBrands: BrandProfile[]): { fileName: string; exportName: string } {
	const last = findLastChunkFile();
	if (last.currentCount >= CHUNK_SIZE_CAP) {
		return createNewChunkFile(last.num + 1, newBrands);
	}

	const filePath = path.join(BRANDS_DIR, last.fileName);
	const fileText = readFileSync(filePath, "utf-8");

	const entriesText = newBrands
		.map((b) => `\t${serialize(b, "\t", 1)},\r\n`)
		.join("");

	const updated = appendBeforeArrayClose(fileText, "];", entriesText);
	writeFileSync(filePath, updated);
	return { fileName: last.fileName, exportName: last.exportName };
}

function appendToStockTags(newTagConfigs: { ticker: string; sourceSection: string; primaryCategory: string; displayTags: string[]; learningTags: { tag: string; weight: number }[] }[]): void {
	const fileText = readFileSync(STOCKTAGS_FILE, "utf-8");

	const entriesText = newTagConfigs
		.map((cfg) => `  ${serialize(cfg, "  ", 1)},\r\n`)
		.join("");

	const updated = appendBeforeArrayClose(fileText, "] as const;", entriesText);
	writeFileSync(STOCKTAGS_FILE, updated);
}

// ── Validation ────────────────────────────────────────────────────────────────

const FINANCIAL_METRIC_KEYS = ["peRatio", "marketCap", "revenueGrowth", "profitMargin", "beta", "dividendYield"] as const;

// Gemini's response is only JSON.parse()'d in brandGenerationService.ts, never
// shape-checked there -- this is the actual gate that must catch a malformed or
// incomplete response (missing field, short array, etc.) before it can commit.
export function validateDraft(draft: BrandDraft, existingTickers: Set<string>): string[] {
	const errors: string[] = [];
	const ticker = draft.ticker?.toUpperCase();
	if (!ticker) errors.push("ticker is required");
	else if (ticker !== draft.ticker) errors.push(`ticker "${draft.ticker}" must be uppercase`);
	else if (existingTickers.has(ticker)) errors.push(`ticker "${ticker}" already exists in the catalog`);
	if (!draft.id) errors.push("id is required");
	if (!draft.name) errors.push("name is required");
	if (!draft.bio) errors.push("bio is required");
	if (!draft.personalityDescription) errors.push("personalityDescription is required");
	if (!draft.vibes || draft.vibes.length !== 3) errors.push(`vibes must have exactly 3 entries, got ${draft.vibes?.length ?? 0}`);
	if (!draft.culturalContext?.title) errors.push("culturalContext.title is required");
	if (!draft.culturalContext?.sections || draft.culturalContext.sections.length === 0) errors.push("culturalContext.sections must have at least 1 entry");
	else {
		for (const [i, section] of draft.culturalContext.sections.entries()) {
			if (!section.heading || !section.content) errors.push(`culturalContext.sections[${i}] is missing heading or content`);
		}
	}
	for (const key of FINANCIAL_METRIC_KEYS) {
		if (!draft.financials?.[key]?.culturalTranslation) errors.push(`financials.${key}.culturalTranslation is required`);
	}
	if (!draft.primaryCategory) errors.push("primaryCategory is required");
	if (!draft.learningTags || draft.learningTags.length === 0) errors.push("learningTags must have at least 1 entry");
	return errors;
}

export interface CommitResult {
	committed: string[];
	chunkFile: string;
	errors: { ticker: string; errors: string[] }[];
}

// `brands` (from @stak/shared) is loaded once at process boot and never
// re-imported afterward, so it doesn't reflect tickers committed by an
// earlier call to commitBrandDrafts() within the SAME running process --
// without tracking those separately, committing the same ticker twice before
// a restart would silently double-append it instead of being rejected as a
// duplicate. This Set starts from `brands` and accumulates every commit.
// (This only protects a single process; horizontally-scaled instances would
// need a real lock/datastore, out of scope for this file-based tool.)
const committedThisProcess = new Set(brands.map((b) => b.ticker.toUpperCase()));

/**
 * Takes one or more human-reviewed BrandDraft objects and appends them to the
 * real shared/src/brands/<last chunk>.ts and shared/src/stockTags.ts files --
 * by text-appending before each file's closing array bracket, never by
 * reformatting or re-serializing entries that are already there. Rejects any
 * draft that fails basic shape validation or duplicates an existing ticker;
 * valid drafts in the same batch still commit even if others are rejected.
 */
export function commitBrandDrafts(drafts: BrandDraft[]): CommitResult {
	const existingTickers = committedThisProcess;
	const valid: BrandDraft[] = [];
	const errors: { ticker: string; errors: string[] }[] = [];

	for (const draft of drafts) {
		const draftErrors = validateDraft(draft, existingTickers);
		if (draftErrors.length > 0) {
			errors.push({ ticker: draft.ticker ?? "(missing)", errors: draftErrors });
		} else {
			valid.push(draft);
			existingTickers.add(draft.ticker.toUpperCase()); // guards against dupes within this batch AND across separate calls (see committedThisProcess above)
		}
	}

	if (valid.length === 0) {
		return { committed: [], chunkFile: "", errors };
	}

	const brandProfiles: BrandProfile[] = valid.map(({ sourceSection, primaryCategory, displayTags, learningTags, ...rest }) => rest);
	const { fileName } = appendBrandsToChunk(brandProfiles);

	const tagConfigs = valid.map((d) => ({
		ticker: d.ticker,
		sourceSection: d.sourceSection,
		primaryCategory: d.primaryCategory,
		displayTags: d.displayTags,
		learningTags: d.learningTags,
	}));
	appendToStockTags(tagConfigs);

	return { committed: valid.map((d) => d.ticker), chunkFile: fileName, errors };
}
