/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MyStakRouteImport } from './routes/my-stak'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileSecurityRouteImport } from './routes/profile_.security'
import { Route as ProfilePersonalDetailsRouteImport } from './routes/profile_.personal-details'
import { Route as ProfileHelpSupportRouteImport } from './routes/profile_.help-support'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MyStakRoute = MyStakRouteImport.update({
  id: '/my-stak',
  path: '/my-stak',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSecurityRoute = ProfileSecurityRouteImport.update({
  id: '/profile_/security',
  path: '/profile/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilePersonalDetailsRoute = ProfilePersonalDetailsRouteImport.update({
  id: '/profile_/personal-details',
  path: '/profile/personal-details',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileHelpSupportRoute = ProfileHelpSupportRouteImport.update({
  id: '/profile_/help-support',
  path: '/profile/help-support',
  getParentRoute: () => rootRouteImport,
} as any)
export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/my-stak': typeof MyStakRoute
  '/onboarding': typeof OnboardingRoute
  '/playground': typeof PlaygroundRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/profile/help-support': typeof ProfileHelpSupportRoute
  '/profile/personal-details': typeof ProfilePersonalDetailsRoute
  '/profile/security': typeof ProfileSecurityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/my-stak': typeof MyStakRoute
  '/onboarding': typeof OnboardingRoute
  '/playground': typeof PlaygroundRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/profile/help-support': typeof ProfileHelpSupportRoute
  '/profile/personal-details': typeof ProfilePersonalDetailsRoute
  '/profile/security': typeof ProfileSecurityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/feed': typeof FeedRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/my-stak': typeof MyStakRoute
  '/onboarding': typeof OnboardingRoute
  '/playground': typeof PlaygroundRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/profile_/help-support': typeof ProfileHelpSupportRoute
  '/profile_/personal-details': typeof ProfilePersonalDetailsRoute
  '/profile_/security': typeof ProfileSecurityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/feed'
    | '/forgot-password'
    | '/login'
    | '/my-stak'
    | '/onboarding'
    | '/playground'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/welcome'
    | '/profile/help-support'
    | '/profile/personal-details'
    | '/profile/security'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/feed'
    | '/forgot-password'
    | '/login'
    | '/my-stak'
    | '/onboarding'
    | '/playground'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/welcome'
    | '/profile/help-support'
    | '/profile/personal-details'
    | '/profile/security'
  id:
    | '__root__'
    | '/'
    | '/feed'
    | '/forgot-password'
    | '/login'
    | '/my-stak'
    | '/onboarding'
    | '/playground'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/welcome'
    | '/profile_/help-support'
    | '/profile_/personal-details'
    | '/profile_/security'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeedRoute: typeof FeedRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MyStakRoute: typeof MyStakRoute
  OnboardingRoute: typeof OnboardingRoute
  PlaygroundRoute: typeof PlaygroundRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  WelcomeRoute: typeof WelcomeRoute
  ProfileHelpSupportRoute: typeof ProfileHelpSupportRoute
  ProfilePersonalDetailsRoute: typeof ProfilePersonalDetailsRoute
  ProfileSecurityRoute: typeof ProfileSecurityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-stak': {
      id: '/my-stak'
      path: '/my-stak'
      fullPath: '/my-stak'
      preLoaderRoute: typeof MyStakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/security': {
      id: '/profile_/security'
      path: '/profile/security'
      fullPath: '/profile/security'
      preLoaderRoute: typeof ProfileSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/personal-details': {
      id: '/profile_/personal-details'
      path: '/profile/personal-details'
      fullPath: '/profile/personal-details'
      preLoaderRoute: typeof ProfilePersonalDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/help-support': {
      id: '/profile_/help-support'
      path: '/profile/help-support'
      fullPath: '/profile/help-support'
      preLoaderRoute: typeof ProfileHelpSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeedRoute: FeedRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MyStakRoute: MyStakRoute,
  OnboardingRoute: OnboardingRoute,
  PlaygroundRoute: PlaygroundRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  WelcomeRoute: WelcomeRoute,
  ProfileHelpSupportRoute: ProfileHelpSupportRoute,
  ProfilePersonalDetailsRoute: ProfilePersonalDetailsRoute,
  ProfileSecurityRoute: ProfileSecurityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
