/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MyStakRouteImport } from './routes/my-stak'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeagueRouteImport } from './routes/league'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeagueResultsRouteImport } from './routes/league_.results'
import { Route as LeaguePerformanceRouteImport } from './routes/league_.performance'
import { Route as LeagueLineupRouteImport } from './routes/league_.lineup'
import { Route as BrandBrandIdRouteImport } from './routes/brand.$brandId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MyStakRoute = MyStakRouteImport.update({
  id: '/my-stak',
  path: '/my-stak',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueRoute = LeagueRouteImport.update({
  id: '/league',
  path: '/league',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueResultsRoute = LeagueResultsRouteImport.update({
  id: '/league_/results',
  path: '/league/results',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguePerformanceRoute = LeaguePerformanceRouteImport.update({
  id: '/league_/performance',
  path: '/league/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueLineupRoute = LeagueLineupRouteImport.update({
  id: '/league_/lineup',
  path: '/league/lineup',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandBrandIdRoute = BrandBrandIdRouteImport.update({
  id: '/brand/$brandId',
  path: '/brand/$brandId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/league': typeof LeagueRoute
  '/login': typeof LoginRoute
  '/my-stak': typeof MyStakRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/brand/$brandId': typeof BrandBrandIdRoute
  '/league/lineup': typeof LeagueLineupRoute
  '/league/performance': typeof LeaguePerformanceRoute
  '/league/results': typeof LeagueResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/league': typeof LeagueRoute
  '/login': typeof LoginRoute
  '/my-stak': typeof MyStakRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/brand/$brandId': typeof BrandBrandIdRoute
  '/league/lineup': typeof LeagueLineupRoute
  '/league/performance': typeof LeaguePerformanceRoute
  '/league/results': typeof LeagueResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/league': typeof LeagueRoute
  '/login': typeof LoginRoute
  '/my-stak': typeof MyStakRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/brand/$brandId': typeof BrandBrandIdRoute
  '/league_/lineup': typeof LeagueLineupRoute
  '/league_/performance': typeof LeaguePerformanceRoute
  '/league_/results': typeof LeagueResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/league'
    | '/login'
    | '/my-stak'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/brand/$brandId'
    | '/league/lineup'
    | '/league/performance'
    | '/league/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/league'
    | '/login'
    | '/my-stak'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/brand/$brandId'
    | '/league/lineup'
    | '/league/performance'
    | '/league/results'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/league'
    | '/login'
    | '/my-stak'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/brand/$brandId'
    | '/league_/lineup'
    | '/league_/performance'
    | '/league_/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LeagueRoute: typeof LeagueRoute
  LoginRoute: typeof LoginRoute
  MyStakRoute: typeof MyStakRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  BrandBrandIdRoute: typeof BrandBrandIdRoute
  LeagueLineupRoute: typeof LeagueLineupRoute
  LeaguePerformanceRoute: typeof LeaguePerformanceRoute
  LeagueResultsRoute: typeof LeagueResultsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-stak': {
      id: '/my-stak'
      path: '/my-stak'
      fullPath: '/my-stak'
      preLoaderRoute: typeof MyStakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league': {
      id: '/league'
      path: '/league'
      fullPath: '/league'
      preLoaderRoute: typeof LeagueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league_/results': {
      id: '/league_/results'
      path: '/league/results'
      fullPath: '/league/results'
      preLoaderRoute: typeof LeagueResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league_/performance': {
      id: '/league_/performance'
      path: '/league/performance'
      fullPath: '/league/performance'
      preLoaderRoute: typeof LeaguePerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league_/lineup': {
      id: '/league_/lineup'
      path: '/league/lineup'
      fullPath: '/league/lineup'
      preLoaderRoute: typeof LeagueLineupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/$brandId': {
      id: '/brand/$brandId'
      path: '/brand/$brandId'
      fullPath: '/brand/$brandId'
      preLoaderRoute: typeof BrandBrandIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LeagueRoute: LeagueRoute,
  LoginRoute: LoginRoute,
  MyStakRoute: MyStakRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  BrandBrandIdRoute: BrandBrandIdRoute,
  LeagueLineupRoute: LeagueLineupRoute,
  LeaguePerformanceRoute: LeaguePerformanceRoute,
  LeagueResultsRoute: LeagueResultsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
