/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MyStakImport } from './routes/my-stak'
import { Route as LeagueImport } from './routes/league'
import { Route as IndexImport } from './routes/index'
import { Route as LeagueResultsImport } from './routes/league.results'
import { Route as LeaguePerformanceImport } from './routes/league.performance'
import { Route as LeagueLineupImport } from './routes/league.lineup'
import { Route as BrandBrandIdImport } from './routes/brand.$brandId'

// Create/Update Routes

const MyStakRoute = MyStakImport.update({
  id: '/my-stak',
  path: '/my-stak',
  getParentRoute: () => rootRoute,
} as any)

const LeagueRoute = LeagueImport.update({
  id: '/league',
  path: '/league',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LeagueResultsRoute = LeagueResultsImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => LeagueRoute,
} as any)

const LeaguePerformanceRoute = LeaguePerformanceImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => LeagueRoute,
} as any)

const LeagueLineupRoute = LeagueLineupImport.update({
  id: '/lineup',
  path: '/lineup',
  getParentRoute: () => LeagueRoute,
} as any)

const BrandBrandIdRoute = BrandBrandIdImport.update({
  id: '/brand/$brandId',
  path: '/brand/$brandId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/league': {
      id: '/league'
      path: '/league'
      fullPath: '/league'
      preLoaderRoute: typeof LeagueImport
      parentRoute: typeof rootRoute
    }
    '/my-stak': {
      id: '/my-stak'
      path: '/my-stak'
      fullPath: '/my-stak'
      preLoaderRoute: typeof MyStakImport
      parentRoute: typeof rootRoute
    }
    '/brand/$brandId': {
      id: '/brand/$brandId'
      path: '/brand/$brandId'
      fullPath: '/brand/$brandId'
      preLoaderRoute: typeof BrandBrandIdImport
      parentRoute: typeof rootRoute
    }
    '/league/lineup': {
      id: '/league/lineup'
      path: '/lineup'
      fullPath: '/league/lineup'
      preLoaderRoute: typeof LeagueLineupImport
      parentRoute: typeof LeagueImport
    }
    '/league/performance': {
      id: '/league/performance'
      path: '/performance'
      fullPath: '/league/performance'
      preLoaderRoute: typeof LeaguePerformanceImport
      parentRoute: typeof LeagueImport
    }
    '/league/results': {
      id: '/league/results'
      path: '/results'
      fullPath: '/league/results'
      preLoaderRoute: typeof LeagueResultsImport
      parentRoute: typeof LeagueImport
    }
  }
}

// Create and export the route tree

interface LeagueRouteChildren {
  LeagueLineupRoute: typeof LeagueLineupRoute
  LeaguePerformanceRoute: typeof LeaguePerformanceRoute
  LeagueResultsRoute: typeof LeagueResultsRoute
}

const LeagueRouteChildren: LeagueRouteChildren = {
  LeagueLineupRoute: LeagueLineupRoute,
  LeaguePerformanceRoute: LeaguePerformanceRoute,
  LeagueResultsRoute: LeagueResultsRoute,
}

const LeagueRouteWithChildren =
  LeagueRoute._addFileChildren(LeagueRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/league': typeof LeagueRouteWithChildren
  '/my-stak': typeof MyStakRoute
  '/brand/$brandId': typeof BrandBrandIdRoute
  '/league/lineup': typeof LeagueLineupRoute
  '/league/performance': typeof LeaguePerformanceRoute
  '/league/results': typeof LeagueResultsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/league': typeof LeagueRouteWithChildren
  '/my-stak': typeof MyStakRoute
  '/brand/$brandId': typeof BrandBrandIdRoute
  '/league/lineup': typeof LeagueLineupRoute
  '/league/performance': typeof LeaguePerformanceRoute
  '/league/results': typeof LeagueResultsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/league': typeof LeagueRouteWithChildren
  '/my-stak': typeof MyStakRoute
  '/brand/$brandId': typeof BrandBrandIdRoute
  '/league/lineup': typeof LeagueLineupRoute
  '/league/performance': typeof LeaguePerformanceRoute
  '/league/results': typeof LeagueResultsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/league'
    | '/my-stak'
    | '/brand/$brandId'
    | '/league/lineup'
    | '/league/performance'
    | '/league/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/league'
    | '/my-stak'
    | '/brand/$brandId'
    | '/league/lineup'
    | '/league/performance'
    | '/league/results'
  id:
    | '__root__'
    | '/'
    | '/league'
    | '/my-stak'
    | '/brand/$brandId'
    | '/league/lineup'
    | '/league/performance'
    | '/league/results'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeagueRoute: typeof LeagueRouteWithChildren
  MyStakRoute: typeof MyStakRoute
  BrandBrandIdRoute: typeof BrandBrandIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeagueRoute: LeagueRouteWithChildren,
  MyStakRoute: MyStakRoute,
  BrandBrandIdRoute: BrandBrandIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/league",
        "/my-stak",
        "/brand/$brandId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/league": {
      "filePath": "league.tsx",
      "children": [
        "/league/lineup",
        "/league/performance",
        "/league/results"
      ]
    },
    "/my-stak": {
      "filePath": "my-stak.tsx"
    },
    "/brand/$brandId": {
      "filePath": "brand.$brandId.tsx"
    },
    "/league/lineup": {
      "filePath": "league.lineup.tsx",
      "parent": "/league"
    },
    "/league/performance": {
      "filePath": "league.performance.tsx",
      "parent": "/league"
    },
    "/league/results": {
      "filePath": "league.results.tsx",
      "parent": "/league"
    }
  }
}
ROUTE_MANIFEST_END */
